apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: vsphere-capacity-manager-vcenter-ctrl
  name: vsphere-capacity-manager-vcenter-ctrl
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vsphere-capacity-manager-vcenter-ctrl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vsphere-capacity-manager-vcenter-ctrl
    spec:
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: quay.io/jcallen/vcm-vcenter:latest
        imagePullPolicy: Always
        name: container
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources: {}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: vsphere-capacity-manager
      serviceAccountName: vsphere-capacity-manager
      terminationGracePeriodSeconds: 30
