---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - vspherecapacitymanager.splat.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vspherecapacitymanager.splat.io
  resources:
  - leases/finalizers
  verbs:
  - update
- apiGroups:
  - vspherecapacitymanager.splat.io
  resources:
  - leases/status
  verbs:
  - get
  - patch
  - update
